baseURL = "http://rubberband.com/"
languageCode = "en-us"
title = "Rubber Band"

description = "Designer first Design System"
theme = "book"
BookMenuBundle= "/menu"

disablePathToLower = true
enableGitInfo = false

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1

[languages.en]
languageName = "English"
contentDir = "content"
weight = 1

[languages.ru]
languageName = "Russian"
contentDir = "content.ru"
weight = 2

[languages.zh]
languageName = "Chinese"
contentDir = "content.zh"
weight = 3

[[menu.after]]
name = "Sketch File"
url = "https://www.sketch.com/s/ea15e306-7a65-43c9-b3dd-a97ad4d974af"
weight = 10

[params]
BookTheme = "light"
BookToC = true
BookSection = "docs"
BookRepo = "https://github.com/snmbala/rubber_band"
BookEditPath = "tree/master"
BookDateFormat = "January 2, 2006"
BookSearch = true
BookComments = true
BookPortableLinks = true
BookServiceWorker = true
BookTranslatedOnly = false

